devops:
  organization: atlas-test
  project: example-403
  repository:
    code:
      name: Example
  build:
    pr:
      name: Example-PR
      path: \Example
      description: Pull request verification build
      queue: Hosted VS2017
      repository: code
      yamlFilename: azure-pipelines.yml
    ci:
      name: Example-CI
      path: \Example
      description: Continuous integration build
      queue: Hosted VS2017
      repository: code
      yamlFilename: azure-pipelines.yml
      continuousIntegration:
        branchFilters:
        - +refs/heads/master
  release:
    cd:
      name: Example-CD
      path: \Example
      description: Continuous deployment release
      queue: Hosted VS2017
      build: ci
      triggerConditions:
      - sourceBranch: master
      stages:
      - name: Stage 1
        steps:
        - taskId: 6c731c3c-3c68-459a-a5c9-bde6e6595b5b # Bash script
          version: 3.*
          enabled: true
          inputs: 
            targetType: inline
            script: echo Hello World
